apiVersion: v1
kind: Pod
metadata:
  name: tailscale-gateway
  labels:
    app: tailscale
spec:
  serviceAccountName: "tailscale"
  containers:
    - name: tailscale
      imagePullPolicy: Always
      image: "ghcr.io/tailscale/tailscale:v1.40.1"
      env:
        - name: TZ
          value: "America/Los_Angeles"
        - name: TS_KUBE_SECRET
          value: "tailscale-auth"
        - name: SA_NAME
          value: tailscale
        - name: TS_USERSPACE
          value: "true"
        - name: TS_ROUTES
          value: "10.244.0.0/16,10.124.0.0/20,10.245.0.0/16"
        # 10.244.0.0/16 pod cidr
        # 10.124.0.0/20 host cidr
        # 10.245.0.0/16 service cidr
        - name: TS_EXTRA_ARGS
          value: "--advertise-exit-node"
      envFrom:
        - secretRef:
            name: tailscale-auth
      resources:
        requests:
          cpu: 100m
          memory: 50Mi
        limits:
          cpu: 100m
          memory: 128Mi
      securityContext:
        runAsUser: 1000
      runAsGroup: 1000
