apiVersion: v1
kind: Service
metadata:
  name: mastodon-streaming
  labels:
    app: mastodon
    component: streaming
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: streaming
      protocol: TCP
      name: streaming
  selector:
    app: mastodon
    component: streaming
