---
clusterName: valinor

talosVersion: v1.4.7
kubernetesVersion: 1.27.3
endpoint: "https://valinor.hsn.dev:6443"

cniConfig:
  name: none

additionalMachineCertSans:
  - valinor.hsn.dev

nodes:
  - hostname: varda.hsn.dev
    disableSearchDomain: true
    ipAddress: 10.2.1.10
    controlPlane: true
    installDisk: /dev/sda
    networkInterfaces:
      - interface: eth0
        dhcp: false
        addresses:
          - 10.2.1.10/24
        routes:
          - network: 10.2.0.0/16
            gateway: 10.2.1.1 # The route's gateway (if empty, creates link scope route).
            metric: 2048
      - interface: eth1
        dhcp: true
        addresses:
          - 192.168.20.10/32
        routes:
          - network: 0.0.0.0/0 # The route's network (destination).
            gateway: 192.168.20.1 # The route's gateway (if empty, creates link scope route).
            metric: 1024
  - hostname: manwe.hsn.dev
    disableSearchDomain: true
    ipAddress: 10.2.1.11
    controlPlane: true
    installDisk: /dev/sda
    networkInterfaces:
      - interface: eth0
        dhcp: false
        addresses:
          - 10.2.1.11/24
        routes:
          - network: 10.2.0.0/16
            gateway: 10.2.1.1 # The route's gateway (if empty, creates link scope route).
            metric: 2048
      - interface: eth1
        dhcp: true
        addresses:
          - 192.168.20.10/24
        routes:
          - network: 0.0.0.0/0 # The route's network (destination).
            gateway: 192.168.20.1 # The route's gateway (if empty, creates link scope route).
            metric: 1024
  - hostname: nienna.hsn.dev
    disableSearchDomain: true
    ipAddress: 10.2.1.12
    controlPlane: true
    installDisk: /dev/vda
    networkInterfaces:
      - interface: eth0
        dhcp: false
        addresses:
          - 10.2.1.12/24
        routes:
          - network: 10.2.0.0/16
            gateway: 10.2.1.1 # The route's gateway (if empty, creates link scope route).
            metric: 2048
      - interface: eth1
        dhcp: true
        routes:
          - network: 0.0.0.0/0 # The route's network (destination).
            gateway: 192.168.20.1 # The route's gateway (if empty, creates link scope route).
            metric: 1024
  - hostname: orome.hsn.dev
    disableSearchDomain: true
    ipAddress: 10.2.1.13
    controlPlane: false
    installDisk: /dev/vda
    networkInterfaces:
      - interface: eth0
        dhcp: false
        addresses:
          - 10.2.1.13/24
        routes:
          - network: 10.2.0.0/16
            gateway: 10.2.1.1 # The route's gateway (if empty, creates link scope route).
            metric: 2048
      - interface: eth1
        dhcp: true
        routes:
          - network: 0.0.0.0/0 # The route's network (destination).
            gateway: 192.168.20.1 # The route's gateway (if empty, creates link scope route).
            metric: 1024
  - hostname: vaire.hsn.dev
    disableSearchDomain: true
    ipAddress: 10.2.1.14
    controlPlane: false
    installDisk: /dev/vda
    networkInterfaces:
      - interface: eth0
        dhcp: false
        addresses:
          - 10.2.1.14/24
        routes:
          - network: 10.2.0.0/16
            gateway: 10.2.1.1 # The route's gateway (if empty, creates link scope route).
            metric: 2048
      - interface: eth1
        dhcp: true
        routes:
          - network: 0.0.0.0/0 # The route's network (destination).
            gateway: 192.168.20.1 # The route's gateway (if empty, creates link scope route).
            metric: 1024
  - hostname: yavanna.hsn.dev
    disableSearchDomain: true
    ipAddress: 10.2.1.15
    controlPlane: false
    installDisk: /dev/vda
    networkInterfaces:
      - interface: eth0
        dhcp: false
        addresses:
          - 10.2.1.15/24
        routes:
          - network: 10.2.0.0/16
            gateway: 10.2.1.1 # The route's gateway (if empty, creates link scope route).
            metric: 2048
      - interface: eth1
        dhcp: true
        routes:
          - network: 0.0.0.0/0 # The route's network (destination).
            gateway: 192.168.20.1 # The route's gateway (if empty, creates link scope route).
            metric: 1024

controlPlane:
  patches:
    - |-
      cluster:
        allowSchedulingOnMasters: true
        proxy:
          disabled: true
        etcd:
          advertisedSubnets:
            - 10.2.1.0/24
        extraManifests:
          - https://raw.githubusercontent.com/jahanson/masto-ops/main/infrastructure/talos/valinor/integrations/cni/cilium.yaml
          - https://raw.githubusercontent.com/jahanson/masto-ops/main/infrastructure/talos/valinor/integrations/kubelet-csr-approver/kubelet-csr-approver.yaml
    - |-
      machine:
        files:
          - op: create
            path: /etc/cri/conf.d/20-customization.part
            content: |
              [plugins]
                [plugins."io.containerd.grpc.v1.cri"]
                  enable_unprivileged_ports = true
                  enable_unprivileged_icmp = true
        kubelet:
          extraArgs:
            feature-gates: CronJobTimeZone=true,GracefulNodeShutdown=true,NewVolumeManagerReconstruction=false
            rotate-server-certificates: "true"
          extraConfig:
            maxPods: 150
        sysctls:
          fs.inotify.max_user_watches: "1048576"
          fs.inotify.max_user_instances: "8192"
        time:
          disabled: false
          servers:
            - time.cloudflare.com
    - |-
      - op: remove
        path: /cluster/apiServer/admissionControl
