---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-vpn-tailscale-gateway
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/valinor/apps/vpn/tailscale-gateway/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: masto-ops-valinor
  wait: true
  dependsOn:
    - name: cluster-apps-external-secrets-stores
