---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: postgres
  namespace: database
spec:
  teamId: "jahanson"

  volume:
    size: 30Gi

  numberOfInstances: 3

  users:
    postgres: # database owner
      - superuser
      - createdb

  postgresql:
    version: "15"
    parameters:
      max_connections: "300"
  sidecars:
    - name: "exporter"
      image: "wrouesnel/postgres_exporter@sha256:54bd3ba6bc39a9da2bf382667db4dc249c96e4cfc837dafe91d6cc7d362829e0"
      ports:
        - name: exporter
          containerPort: 9187
          protocol: TCP
      resources:
        requests:
          cpu: 10m
          memory: 32M
        limits:
          cpu: 50m
          memory: 109M
      env:
        - name: "DATA_SOURCE_URI"
          value: "postgres-ext.database.svc.cluster.local/postgres"
        - name: "DATA_SOURCE_USER"
          valueFrom:
            secretKeyRef:
              name: postgres.postgres.credentials.postgresql.acid.zalan.do
              key: username
        - name: "DATA_SOURCE_PASS"
          valueFrom:
            secretKeyRef:
              name: postgres.postgres.credentials.postgresql.acid.zalan.do
              key: password
  # Restore procedure:
  # - Remove the existing cluster
  # - Uncomment the "clone" section below to restore a point in time backup
  # - Apply the config and let the cluster restore
  # - Uncomment the "clone" section below
  # clone:
  #   cluster: "postgres"  # The source cluster name
  #   timestamp: "2023-03-21T19:50:00+00:00"  # timezone required (offset relative to UTC, see RFC 3339 section 5.6)
