---
apiVersion: v1
kind: Service
metadata:
  name: postgres-ext
  namespace: database
spec:
  type: ClusterIP
  externalTrafficPolicy: Local
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    application: spilo
    cluster-name: postgres
    spilo-role: master
---
apiVersion: v1
kind: Service
metadata:
  name: pg-exporter
  namespace: database
  labels:
    app: pg-exporter
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
    - name: exporter
      port: 9187
      targetPort: exporter
  selector:
    application: spilo
    team: jahanson
