---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nginx-ingress-secrets
  namespace: network
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: nginx-ingress
  target:
    name: nginx-ingress-secrets
    creationPolicy: Owner
  data:
    - secretKey: nginx-ingress-bouncer-apikey
      remoteRef:
        key: Crowdsec
        property: nginx-ingress-bouncer
