---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-web
  namespace: fediverse
  labels:
    app: mastodon
    component: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mastodon
      component: web
  template:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        app: mastodon
        component: web
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - mastodon
                  - key: component
                    operator: In
                    values:
                      - web
              topologyKey: kubernetes.io/hostname
      containers:
        - name: mastodon-web
          image: ghcr.io/mastodon/mastodon:v4.1.2@sha256:6b18e6d0eda476397d48cc36ac040b5da9c73503e374708a815a7f76db740576
          command:
            - bundle
            - exec
            - puma
            - -C
            - config/puma.rb
          imagePullPolicy: IfNotPresent
          tty: true
          envFrom:
            - secretRef:
                name: mastodon-secret
          resources:
            requests:
              cpu: 15m
              memory: 50Mi
            limits:
              memory: 250Mi
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          startupProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 30
            periodSeconds: 5
