apiVersion: v1
kind: Service
metadata:
  name: mastodon-web
  labels:
    app: mastodon
    component: web
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: mastodon
    component: web
