---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mastodon
  namespace: fediverse
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mastodon-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        LOCAL_DOMAIN: "valinor.social"
        SINGLE_USER_MODE: "false"
        SECRET_KEY_BASE: "{{ .mastodon_secret_key_base }}"
        OTP_SECRET: "{{ .mastodon_otp_secret }}"
        VAPID_PRIVATE_KEY: "{{ .mastodon_vapid_private_key }}"
        VAPID_PUBLIC_KEY: "{{ .mastodon_vapid_public_key }}"
        DB_HOST: "{{ .mastodon_db_host }}"
        DB_PORT: "5432"
        DB_NAME: "mastodon"
        DB_USER: "mastodon"
        DB_PASS: "{{ .mastodon_postgres_password }}"
        REDIS_URL: "{{ .mastodon_redis_url }}"
        S3_ENABLED: "true"
        S3_PROTOCOL: "https"
        S3_REGION: "us-east-1"
        S3_ENDPOINT: "https://s3m.hsn.dev"
        S3_HOSTNAME: "s3m.hsn.dev"
        S3_BUCKET: "mastodon"
        AWS_ACCESS_KEY_ID: "{{ .minio_mastodon_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ .minio_mastodon_secret_key }}"
        SMTP_SERVER: "smtp.mailgun.org"
        SMTP_PORT: "587"
        SMTP_LOGIN: "{{ .mailgun_smtp_user }}"
        SMTP_PASSWORD: "{{ .mailgun_smtp_password }}"
        SMTP_AUTH_METHOD: "plain"
        SMTP_OPENSSL_VERIFY_MODE: "peer"
        SMTP_ENABLE_STARTTLS: "auto"
        SMTP_FROM_ADDRESS: "Mastodon <notifications@valinor.social>"
        DB_POOL: "25" # needs to match concurrency in mastodon-sidekiq deployment.yaml
        DEEPL_PLAN: "free"
        DEEPL_API_KEY: "{{ .deepl_api_key }}"
        ES_ENABLED: "true"
        ES_HOST: "{{ .mastodon_es_host }}"
        ES_PORT: "{{ .mastodon_es_port }}"
        ES_PASS: "{{ .mastodon_es_pass }}"
        STATSD_ADDR: "statsd-exporter.fediverse.svc.cluster.local:9125"
  dataFrom:
    - extract:
        key: minio-s3m
      rewrite:
        - regexp:
            source: "(.*)"
            target: "minio_$1"
    - extract:
        key: mastodon
      rewrite:
        - regexp:
            source: "(.*)"
            target: "mastodon_$1"
  data:
    - secretKey: mailgun_smtp_user
      remoteRef:
        key: mailgun
        property: mastodon_smtp_user
    - secretKey: mailgun_smtp_password
      remoteRef:
        key: mailgun
        property: mastodon_smtp_password
    - secretKey: deepl_api_key
      remoteRef:
        key: deepl
        property: api_key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-auth
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: tailscale-auth
    creationPolicy: Owner
  data:
    - secretKey: TS_AUTH_KEY
      remoteRef:
        key: tailscale
        property: ts_auth_key
