---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elk
  namespace: fediverse
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/elk-zone/elk
      tag: v0.9.7@sha256:923ee71ef83026c8c0a5cb82b9c6460455e92d7a27a2af1204f8711150889d70

    env:
      NUXT_PUBLIC_DEFAULT_SERVER: "valinor.social"
    # envFrom:
    #   - secretRef:
    #       name: elk-secret

    podSecurityContext:
      runAsUser: 911
      runAsGroup: 911
      fsGroup: 911
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 65539

    service:
      main:
        ports:
          http:
            port: 5314

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress.valinor.social
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
        hosts:
          - host: &host "elk.valinor.social"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        # existingClaim: elk-config
        mountPath: /elk/data

    resources:
      requests:
        cpu: 15m
        memory: 64M
      limits:
        cpu: 46m
        memory: 154M
