---
creation_rules:
  - path_regex: kubernetes/(global|valinor)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    # Valinor
    age: >-
      age14qslan3wn5sjtsyc74qt976hm0s0u6zjufnqz822uuwyg08krdaq4vu4yu
  - path_regex: .*\.sops\.env
    # Valinor
    age: >-
      age14qslan3wn5sjtsyc74qt976hm0s0u6zjufnqz822uuwyg08krdaq4vu4yu
