---
creation_rules:
  - path_regex: kubernetes/(global|valinor)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    # Valinor
    age: >-
      age1f5pr5rss0n8z4d6r8kky9umr5g48tt03reuyjushw5kayrpsxvgsw80gsj
  - path_regex: .*\.sops\.env
    # Valinor
    age: >-
      age1f5pr5rss0n8z4d6r8kky9umr5g48tt03reuyjushw5kayrpsxvgsw80gsj
