data_dir: /vector-data-dir

api:
  enabled: false

# Sources
sources:
  kubernetes_logs:
    type: kubernetes_logs
    use_apiserver_cache: true

# Sinks
sinks:
  kubernetes_sink:
    type: vector
    compression: true
    inputs:
      - kubernetes_logs
    address: "100.77.50.79:6000"
    version: "2"
