---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: thanos
      version: 12.6.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 30m
  values:
    objstoreConfig:
      type: s3

    query:
      enabled: true
      dnsDiscovery:
        sidecarsService: kube-prometheus-stack-thanos-discovery
        sidecarsNamespace: monitoring
      replicaLabels:
        - "__replica__" # must match with kube-prometheus-stack value `.prometheus.prometheusSpec.replicaExternalLabelName`
      resources:
        requests:
          cpu: 15m
          memory: 110M
        limits:
          cpu: 200m
        # limits:
        #   memory: 99M

    queryFrontend:
      enabled: true
      ingress:
        enabled: true
        hostname: "thanos.valinor.social"
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
        tls: true

    bucketweb:
      enabled: true
      resources:
        requests:
          cpu: 15m
          memory: 64M
        limits:
          cpu: 45m
          memory: 152M

    compactor:
      enabled: true
      extraFlags:
        - "--compact.concurrency"
        - "4"
      retentionResolutionRaw: 14d
      retentionResolution5m: 14d
      retentionResolution1h: 30d
      resources:
        requests:
          cpu: 15m
          memory: 100Mi
        limits:
          cpu: 96m
          memory: 1024Mi
      persistence:
        enabled: true
        size: 30Gi

    storegateway:
      enabled: true
      resources:
        requests:
          cpu: 15m
          memory: 78M
      persistence:
        enabled: true
        size: 1Gi

    ruler:
      enabled: true
      alertmanagers:
        - http://alertmanager.monitoring.svc.cluster.local:9093
      clusterName: valinor # must match with kube-prometheus-stack value `.prometheus.prometheusSpec.externalLabels.cluster`
      config: |-
        groups:
          - name: "PrometheusWatcher"
            rules:
              - alert: "PrometheusDown"
                expr: absent(up{job="kube-prometheus-stack-prometheus"})
      dnsDiscovery:
        enabled: true
      persistence:
        enabled: true
        size: 512Mi
      resources:
        requests:
          cpu: 15m
          memory: 36Mi
        limits:
          cpu: 46m
          memory: 36Mi

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  valuesFrom:
    - kind: Secret
      name: thanos-secret
      valuesKey: S3_BUCKET_NAME
      targetPath: objstoreConfig.config.bucket
    - kind: Secret
      name: thanos-secret
      valuesKey: S3_BUCKET_HOST
      targetPath: objstoreConfig.config.endpoint
    - kind: Secret
      name: thanos-secret
      valuesKey: S3_BUCKET_REGION
      targetPath: objstoreConfig.config.region
    - kind: Secret
      name: thanos-secret
      valuesKey: S3_ACCESS_KEY
      targetPath: objstoreConfig.config.access_key
    - kind: Secret
      name: thanos-secret
      valuesKey: S3_SECRET_KEY
      targetPath: objstoreConfig.config.secret_key
