---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  chart:
    spec:
      chart: cilium
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      version: 1.13.3
  interval: 30m

  valuesFrom:
    - kind: ConfigMap
      name: cilium-values

  values:
    hubble:
      ui:
        ingress:
          enabled: true
          annotations:
            nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
          className: "nginx"
          hosts:
            - &host hubble-morgoth.valinor.social
          tls:
            - hosts:
                - *host
    #   metrics:
    #     serviceMonitor:
    #       enabled: true
    #   relay:
    #     prometheus:
    #       serviceMonitor:
    #         enabled: true
    # prometheus:
    #   serviceMonitor:
    #     enabled: true
    # operator:
    #   prometheus:
    #     serviceMonitor:
    #       enabled: true
