---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-kubelet-csr-approver
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/valinor/apps/kube-system/kubelet-csr-approver/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: masto-ops-valinor
  wait: true
