---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-snapshot-controller
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 10m
  path: "./kubernetes/valinor/apps/kube-system/snapshot-controller/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: masto-ops-valinor
  wait: true
  timeout: 2m
