---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-secret
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: alertmanager-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        values.yaml: |
          alertmanager:
            config:
              receivers:
                - name: heartbeat
                  webhook_configs:
                    - url: {{ .heartbeat_url }}
                - name: pushover
                  token: {{ .pushover_api_token }}
                  user_key: {{ .pushover_api_userkey }}

  data:
    - secretKey: pushover_api_token
      remoteRef:
        key: Pushover
        property: alertmanager_token
    - secretKey: pushover_api_userkey
      remoteRef:
        key: Pushover
        property: userkey_jahanson
    - secretKey: heartbeat_url
      remoteRef:
        key: kube-prometheus-stack
        property: heartbeat_token
