---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-auth
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: tailscale-auth
    creationPolicy: Owner
  data:
    - secretKey: TS_AUTH_KEY
      remoteRef:
        key: tailscale
        property: ts_auth_key
