---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 30m
  maxHistory: 2
  timeout: 20m
  chart:
    spec:
      chart: kube-prometheus
      version: 8.13.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 30m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    prometheus:
      containers:
        - name: tailscale
          imagePullPolicy: Always
          image: "ghcr.io/tailscale/tailscale:v1.42.0"
          env:
            - name: TS_KUBE_SECRET
              value: "tailscale-state"
            - name: SA_NAME
              value: tailscale
            - name: TS_USERSPACE
              value: "false"
            - name: TS_EXTRA_ARGS
              value: "--accept-routes"
          envFrom:
            - secretRef:
                name: tailscale-auth
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 128Mi
          securityContext:
            # privileged: true
            capabilities:
              add:
                - NET_ADMIN
      remoteWrite:
        - url: http://100.81.138.55:19291/api/v1/receive
