---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: echo-server
  namespace: network
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    image:
      repository: ghcr.io/mendhak/http-https-echo
      tag: "29"

    env:
      HTTP_PORT: &port 8080
      LOG_WITHOUT_NEWLINE: "true"
      LOG_IGNORE_PATH: "/healthz"

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: "ingress.valinor.social"
        hosts:
          - host: &host "echo-server.valinor.social"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    resources:
      requests:
        cpu: 15m
        memory: 64M
      limits:
        memory: 128M