---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app mastodon-sidekiq-remote-pull
  namespace: fediverse
  labels:
    app: mastodon
    component: sidekiq
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controller:
      replicas: 1
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        app: mastodon
        component: sidekiq
    image:
      repository: ghcr.io/mastodon/mastodon
      tag: v4.1.5@sha256:61e4dc0026605003be8f26a0008f244fc7b3c4f0dfcf1c5d8f3ef7630d46f90d
    command: ["bundle", "exec", "sidekiq", "-c", "25", "-q", "pull"]
    envFrom:
      - secretRef:
          name: mastodon-secret
    env:
      DB_NAME: "$(CP_SIDEKIQ_PULL)"
      DB_PORT: "${CP_DB_PORT}"
      PREPARED_STATEMENTS: "false" # neccessary for pgbouncer
    service:
      main:
        enabled: false
    # nodeSelector:
    #   doks.digitalocean.com/node-pool: pool-sidekiq
    resources:
      requests:
        cpu: 2000m
        memory: 250Mi
      limits:
        cpu: 3000m
        memory: 800Mi
