---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app mastodon-sidekiq-remote-pull
  namespace: fediverse
  labels:
    app: mastodon
    component: sidekiq
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controller:
      type: daemonset
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        app: mastodon
        component: sidekiq
    image:
      repository: ghcr.io/mastodon/mastodon
      tag: v4.1.2
    command: ["bundle", "exec", "sidekiq", "-c", "25", "-q", "pull"]
    envFrom:
      - secretRef:
          name: mastodon-secret
    env:
      DB_NAME: "$(CP_SIDEKIQ_PULL)"
    service:
      main:
        enabled: false
    affinity:
      podAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: "doks.digitalocean.com/node-pool"
                  operator: In
                  values:
                    - pool-moria-c
            topologyKey: "kubernetes.io/hostname"
    resources:
      requests:
        cpu: 48m
        memory: 250M
      limits:
        cpu: 800m
        memory: 972M
