---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: 
      valueFrom:
        secretKeyRef:
          name: dnsimple-api-token
          key: letsencrypt-email
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt-production
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          webhook:
            config:
              tokenSecretRef:
                key: api-token
                name: dnsimple-api-token
            selector:
              dnsZones:
                - valinor.social
            solverName: dnsimple
            groupName: acme.jahanson.com