---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/valinor/apps/monitoring/kube-prometheus-stack/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: masto-ops-valinor
  wait: true
  dependsOn:
    - name: cluster-apps-alertmanager
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-kube-prometheus-stack-addons
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/valinor/apps/monitoring/kube-prometheus-stack/addons"
  prune: true
  sourceRef:
    kind: GitRepository
    name: masto-ops-valinor
  wait: true
  dependsOn:
    - name: cluster-apps-kube-prometheus-stack
  patches:
    - patch: |
        - op: add
          path: /spec/template/spec/containers/-
          value:
            name: ts-sidecar
            imagePullPolicy: Always
            image: "ghcr.io/tailscale/tailscale:latest"
            env:
              # Store the state in a k8s secret
              - name: TS_KUBE_SECRET
                value: "tailscale"
              - name: TS_USERSPACE
                value: "false"
              - name: TS_AUTHKEY
                valueFrom:
                  secretKeyRef:
                    name: tailscale-auth
                    key: auth_key
                    optional: false
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
      target: # adding tailscale sidecar
        labelSelector: "app=kube-prometheus-stack-prometheus"
        namespace: monitoring
