apiVersion: v1
kind: Pod
metadata:
  name: mastodon-tootctl
  namespace: fediverse
spec:
  containers:
    - name: mastodon-tootctl
      image: tootsuite/mastodon:latest@sha256:6b18e6d0eda476397d48cc36ac040b5da9c73503e374708a815a7f76db740576
      command: ["/bin/bash", "-c", "--"]
      args: ["while true; do sleep 30; done;"]
      envFrom:
        - secretRef:
            name: mastodon-secret
      resources:
        limits:
          cpu: "1"
          memory: "2Gi"
        requests:
          cpu: "500m"
          memory: "256Mi"
