apiVersion: v1
kind: Pod
metadata:
  name: mastodon-tootctl
  namespace: fediverse
spec:
  serviceAccount: mastodon
  containers:
    - name: mastodon-tootctl
      image: tootsuite/mastodon:latest@sha256:6b18e6d0eda476397d48cc36ac040b5da9c73503e374708a815a7f76db740576
      command: ["/bin/bash", "-c", "--"]
      args: ["while true; do sleep 30; done;"]
      envFrom:
        - secretRef:
            name: mastodon-secret
      resources:
        limits:
          cpu: "1"
          memory: "2Gi"
        requests:
          cpu: "50m"
          memory: "256Mi"
    - name: tailscale
      imagePullPolicy: Always
      image: "ghcr.io/tailscale/tailscale:v1.42.0"
      env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: TS_KUBE_SECRET
          value: "tailscale-state-$(MY_NODE_NAME)-mastodon-tootctl"
        - name: TS_USERSPACE
          value: "false"
        - name: TS_EXTRA_ARGS
          value: "--accept-routes"
      envFrom:
        - secretRef:
            name: tailscale-auth
      resources:
        requests:
          cpu: 50m
          memory: 50Mi
        limits:
          cpu: 100m
          memory: 128Mi
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
