apiVersion: v1
kind: Pod
metadata:
  name: mastodon-tootctl
  namespace: fediverse
spec:
  containers:
    - name: mastodon-tootctl
      image: tootsuite/mastodon:latest@sha256:abcbac50f7bf55187f262b7c819e0b1f8260c3a2746578946856c7313f5174bb
      command: ["/bin/bash", "-c", "--"]
      args: ["while true; do sleep 30; done;"]
      envFrom:
        - secretRef:
            name: mastodon-secret
      env:
        - name: DB_NAME
          value: "mastodon"
        - name: DB_PORT
          value: "5432"

      resources:
        limits:
          cpu: "1"
          memory: "2Gi"
        requests:
          cpu: "50m"
          memory: "256Mi"
