---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vector-agent
  namespace: monitoring
spec:
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controller:
      type: daemonset
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/onedr0p/vector
      tag: 0.31.0-debian@sha256:00918218d9c53f62a2f48ed6eeee2fb06ee48a55129ffeb7c713264a2d3f5eab

    args: ["--config", "/etc/vector/vector.yaml"]

    sidecars:
      tailscale:
        imagePullPolicy: Always
        image: "ghcr.io/tailscale/tailscale:v1.42.0"
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: TS_KUBE_SECRET
            value: "tailscale-state-$(MY_NODE_NAME)"
          - name: TS_USERSPACE
            value: "false"
          - name: TS_EXTRA_ARGS
            value: "--accept-routes"
        envFrom:
          - secretRef:
              name: tailscale-auth
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 128Mi
        securityContext:
          capabilities:
            add:
              - NET_ADMIN

    env:
      PROCFS_ROOT: /host/proc
      SYSFS_ROOT: /host/sys
      VECTOR_SELF_NODE_NAME:
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: spec.nodeName
      VECTOR_SELF_POD_NAME:
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
      VECTOR_SELF_POD_NAMESPACE:
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.namespace

    persistence:
      config:
        enabled: true
        type: configMap
        name: vector-agent-configmap
        subPath: vector.yaml
        mountPath: /etc/vector/vector.yaml
        readOnly: true
      data:
        enabled: true
        type: emptyDir
        mountPath: /vector-data-dir
      var-log:
        enabled: true
        type: hostPath
        hostPath: /var/log
        hostPathType: Directory
        mountPath: /var/log
        readOnly: true
      var-lib:
        enabled: true
        type: hostPath
        hostPath: /var/lib
        hostPathType: Directory
        mountPath: /var/lib
        readOnly: true
      procfs:
        enabled: true
        type: hostPath
        hostPath: /proc
        hostPathType: Directory
        mountPath: /host/proc
        readOnly: true
      sysfs:
        enabled: true
        type: hostPath
        hostPath: /sys
        hostPathType: Directory
        mountPath: /host/sys
        readOnly: true

    podMonitor:
      enabled: true

    resources:
      requests:
        cpu: 23m
        memory: 249M

    securityContext:
      privileged: true

    service:
      main:
        enabled: false

    serviceAccount:
      create: true
      name: vector-agent

    tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
