#!/usr/bin/env bash
set -o pipefail

source minimal_network.functions.sh

IFACE_NAME="$(udevadm info -e | grep -m1 -A 20 ^P.*eth0 | grep ID_NET_NAME_PATH | cut -d'=' -f2)"
IPV4_ADDRS=($(network_interface_ipv4_addrs "$IFACE_NAME"))
IPV6_ADDRS=($(network_interface_ipv6_addrs "$IFACE_NAME"))
MAIN_IPV4_CIDR="${IPV4_ADDRS[0]}"
MAIN_IPV4_GW=$(network_interface_ipv4_gateway "$IFACE_NAME")
MAIN_IPV6_CIDR="${IPV6_ADDRS[0]}"
MAIN_IPV6_GW=$(network_interface_ipv6_gateway "$IFACE_NAME")
NETMASK="$(ipv4_addr_netmask "${IPV4_ADDRS[0]}")"
NETWORK="$(ipv4_addr_network "${IPV4_ADDRS[0]}")"
NETWORK_WITHOUT_SUFFIX="$(ip_addr_without_suffix "$NETWORK")"

template=$(cat <<EOF
# network interface settings; autogenerated
# Please do NOT modify this file directly, unless you know what
# you're doing.
#
# If you want to manage parts of the network configuration manually,
# please utilize the 'source' or 'source-directory' directives to do
# so.
# PVE will preserve these directives, but will NOT read its network
# configuration from sourced files, so do not attempt to move any of
# the PVE managed interfaces into external files!

source /etc/network/interfaces.d/*

auto lo
iface lo inet loopback

iface lo inet6 loopback

auto #IFACE_NAME#
iface #IFACE_NAME# inet static
    address #MAIN_IPV4_CIDR#
    gateway #MAIN_IPV4_GW#
    # route #NETWORK# via #MAIN_IPV4_GW#
    up route add -net #NETWORK_WITHOUT_SUFFIX# netmask #NETMASK# gw #MAIN_IPV4_GW# dev #IFACE_NAME#

iface enp5s0 inet6 static
    address #MAIN_IPV6_CIDR#
    gateway #MAIN_IPV6_GW#

auto vmbr0
iface vmbr0 inet manual
    bridge-ports #IFACE_NAME#.4010
    bridge-stp off
    bridge-fd 0

auto vmbr1
iface vmbr1 inet static
    address 192.168.20.1/24
    bridge-ports none
    bridge-stp off
    bridge-fd 0
    post-up   iptables -t nat -A POSTROUTING -s '192.168.20.0/24' -o #IFACE_NAME# -j MASQUERADE
    post-down iptables -t nat -D POSTROUTING -s '192.168.20.0/24' -o #IFACE_NAME# -j MASQUERADE
    post-up   iptables -t raw -I PREROUTING -i fwbr+ -j CT --zone 1
    post-down iptables -t raw -D PREROUTING -i fwbr+ -j CT --zone 1
EOF
)

# replace variables in template
template=$(echo "$template" | sed "s|#IFACE_NAME#|$IFACE_NAME|g")
template=$(echo "$template" | sed "s|#MAIN_IPV4_CIDR#|$MAIN_IPV4_CIDR|g")
template=$(echo "$template" | sed "s|#MAIN_IPV4_GW#|$MAIN_IPV4_GW|g")
template=$(echo "$template" | sed "s|#MAIN_IPV6_CIDR#|$MAIN_IPV6_CIDR|g")
template=$(echo "$template" | sed "s|#MAIN_IPV6_GW#|$MAIN_IPV6_GW|g")
template=$(echo "$template" | sed "s|#NETMASK#|$NETMASK|g")
template=$(echo "$template" | sed "s|#NETWORK#|$NETWORK|g")
template=$(echo "$template" | sed "s|#NETWORK_WITHOUT_SUFFIX#|$NETWORK_WITHOUT_SUFFIX|g")

# echo $template to be used by pipe
echo "$template"
