---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-database-dragonflydb
  namespace: flux-system
spec:
  interval: 30m
  path: "./kubernetes/valinor/apps/database/dragonflydb/app"
  prune: false
  sourceRef:
    kind: GitRepository
    name: masto-ops-valinor
  wait: false # no flux ks dependents
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-database-dragonflydb-standalone
  namespace: flux-system
spec:
  interval: 30m
  path: "./kubernetes/valinor/apps/database/dragonflydb/standalone"
  prune: false
  sourceRef:
    kind: GitRepository
    name: masto-ops-valinor
  wait: false # no flux ks dependents
