---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-sidekiq
  namespace: fediverse
  labels:
    app: mastodon
    component: sidekiq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mastodon
      component: sidekiq
  template:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        app: mastodon
        component: sidekiq
    spec:
      containers:
        - name: mastodon-sidekiq
          image: ghcr.io/mastodon/mastodon:v4.1.2@sha256:6b18e6d0eda476397d48cc36ac040b5da9c73503e374708a815a7f76db740576
          command: [
            "bundle",
            "exec",
            "sidekiq",
            "-c",
            "25",
            "-q",
            "default,8",
            "-q",
            "push,6",
            "-q",
            "ingress,4",
            "-q",
            "mailers,2",
            "-q",
            "pull",
            "-q",
            "scheduler"
          ]
          imagePullPolicy: IfNotPresent
          tty: true
          envFrom:
            - secretRef:
                name: mastodon-secret
          resources:
            requests:
              cpu: 48m
              memory: 250M
            limits:
              memory: 972M
