---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: masto-ops-valinor
  namespace: flux-system
spec:
  interval: 30m
  ref:
    branch: main
  url: https://github.com/jahanson/valinor.git
  ignore: |
    # exclude all
    /*
    # include gitops dirs
    !/kubernetes
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/valinor/flux
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: masto-ops-valinor
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: flux
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
        optional: false